### ISSUE TITLE
Any description on how to use it?

### ISSUE THREAD

**Issue by McTristan** [Voder/nodered-sonnen-nrgkick-flow#1]
@Voder 

Can you please provide a small documentation on how to use it?
In the nrgkick app I can only provide an IP address oder hostname and a port. If you have your flows running under the /endpoint/-route I don't see how this would work with the app?

Maybe you can share some more details or screenshots?

Thanks a lot!

**Comment by Voder** [comment]
Hi @McTristan,
i added some more explanation to the README.

The node-RED flow serves the 2 endpoints which are expected by the nrgkick app with custom api configuration.
So when your node-red instance runs under e.g. `192.168.1.123:1880`, the flow creates the 2 endpoints `192.168.1.123:1880/api/v1/info.json` and `192.168.1.123:1880/api/v1/values.json`. Your nrgkick app only needs the server ip and port and queries the 2 paths for information and values.

You can read more about the custom api approach in the [official nrgkick documentation](https://www.nrgkick.com/wp-content/uploads/2024/02/20240220_Anleitung-zum-PV-Laden-mit-NRGkick_custom-API.pdf).

Hope it helps.

**Comment by McTristan** [comment]
Ah ok it works only when nodered endpoints are configured to be served from root. When using homeassistant endpoints are server under "/endpoint/api/v1/info.json" so it wouldn't work for nrgkick. I've managed to get it working from a sample python script provided by nrgkick. As a workaround I'm fetching the nodered endpoints and just forward the json. That works for me.
Thank you for clarifying it!
